---
title: "Tree_temp_data_wrangling"
author: "Erika Lee"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
{r}
#installing packages / set working directory
#packages <- c('tidyverse',
             # 'lterdatasampler', 'dplyr', 'ggplot2', 'readr', 'readxl', 'lubridate', 'plotly', 'openxlsx', 'plotly', 'rstatix')

#install.packages(packages)

library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)
library(htmlwidgets)

#install.packages("RColorBrewer")
library(RColorBrewer)
```

```{r}
#install.packages("officer")
library(officer)

#install.packages("rvg")
library(rvg)

#install.packages("here")
library(here)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

```{r}
#calling in dataframes as excels fron N-Drive
pers_b_aspects <- read_excel("nsf/105E_pers_burned/105E_pers_b_aspects.xlsx")

trans_b_aspects <- read_excel("nsf/105E_trans_burned/105E_trans_b_aspects.xlsx")

pers_n_gb_temp <- read_excel("nsf/105E_pers_burned/pers_n_gb_temp.xlsx")

pers_n_db_temp <- read_excel("nsf/105E_pers_burned/pers_n_db_temp.xlsx")

pers_s_gb_temp <- read_excel("nsf/105E_pers_burned/pers_s_gb_temp.xlsx")

pers_s_db_temp <- read_excel("nsf/105E_pers_burned/pers_s_db_temp.xlsx")

trans_n_gb_temp <- read_excel("nsf/105E_trans_burned/trans_n_gb_temp.xlsx")

trans_n_db_temp <- read_excel("nsf/105E_trans_burned/trans_n_db_temp.xlsx")

trans_s_gb_temp <- read_excel("nsf/105E_trans_burned/trans_s_gb_temp.xlsx")

trans_s_db_temp <- read_excel("nsf/105E_trans_burned/trans_s_db_temp.xlsx")
```

```{r}
#creating north aspect dataframe

##persistent_n sensors
all_pers_n_sensors <- pers_n_gb_temp %>%
  full_join(pers_n_db_temp) %>%
  #select("tree_name" == c("gb_e", "db_n")) %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "persistent") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "north_gb_s_tree",
    tree_name == "gb_e" ~ "north_gb_e_tree",
    tree_name == "db_s" ~ "north_db_s_tree",
    tree_name == "db_n" ~ "north_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  filter(!(burn_status == "gb_w"))

##transitional_n sensors
all_trans_n_sensors <- trans_n_gb_temp %>%
  full_join(trans_n_db_temp) %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  #select("tree_name" == c("gb_n", "db_n")) %>%
  select(-"sensor_id") %>%
  mutate(zone = "transitional") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "north_gb_s_tree",
    tree_name == "gb_n" ~ "north_gb_n_tree",
    tree_name == "db_s" ~ "north_db_s_tree",
    tree_name == "db_n" ~ "north_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))

##combining n sensor dataframes
all_n_sensors <- all_pers_n_sensors %>%
  full_join(all_trans_n_sensors)
```

```{r}
##creating dataframes for pers_n_db and trans_n_db with two trees per dataframe, then combining into one dataframe 
pers_n_db_sensors <- pers_n_db_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "persistent") %>%
  mutate(burn_status = case_when(
    tree_name == "db_s" ~ "north_db_s_tree",
    tree_name == "db_n" ~ "north_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))

trans_n_db_sensors <- trans_n_db_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "transitional") %>%
  mutate(burn_status = case_when(
    tree_name == "db_s" ~ "north_db_s_tree",
    tree_name == "db_n" ~ "north_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#plotting all_n_db_sensors_plot 

all_n_db_sensors_plot <-  ggplot() +
  geom_line(data = trans_n_db_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Transitional"), alpha = 0.5) +
  geom_line(data = pers_n_db_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Persistent"), alpha = 0.3) +
scale_color_manual(values = c("blue", "red", "blue", "red"), name = "aspect_burnstatus_treename,") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "Zone") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent DB North Sensors")

ggplotly(all_n_db_sensors_plot)

#making into a plotly instead of a ggplot
plotly_all_n_db_sensors_plot <- ggplotly(all_n_db_sensors_plot)
```

```{r}
#exporting to hmtl
htmlwidgets::saveWidget(plotly_all_n_db_sensors_plot, "all_n_db_sensors_plot.html")
```

```{r}
##NOT USING THIS CODE CHUNK!
all_n_db_sensors_plot_dml <- rvg::dml(ggobj = all_n_db_sensors_plot)

#initializing powerpoint slide
officer::read_pptx() %>%
  # add slide ----
  officer::add_slide() %>%
  # specify object and location of object ----
  officer::ph_with(all_n_db_sensors_plot_dml, ph_location()) %>%
  # export slide -----
  base::print(target = "/Users/erikalee/Documents/CSU_Classes/R_work/nsf_project_code/nsf_project/graphics/all_n_db_sensors_plot.pptx")
```

```{r}
##creating dataframes for pers_s_db and trans_s_db with two trees per dataframe, then combining into one dataframe 
pers_s_db_sensors <- pers_s_db_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "persistent") %>%
  mutate(burn_status = case_when(
    tree_name == "db_s" ~ "south_db_s_tree",
    tree_name == "db_n" ~ "south_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))

trans_s_db_sensors <- trans_s_db_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "transitional") %>%
  mutate(burn_status = case_when(
    tree_name == "db_s" ~ "south_db_s_tree",
    tree_name == "db_n" ~ "south_db_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#plotting all_s_db_sensors_plot 
all_s_db_sensors_plot <- ggplot() +
  geom_line(data = trans_s_db_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Transitional"), alpha = 0.5) +
  geom_line(data = pers_s_db_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Persistent"), alpha = 0.3) +
  scale_color_manual(values = c("blue", "red", "blue", "red"), name = "aspect_burnstatus_treename,") + 
scale_linetype_manual(values = c("solid", "dashed"), name = "Zone") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent Dead Burn Tree South Sensors")

ggplotly(all_s_db_sensors_plot)

#converting plot to plotly inorder to export as a widget
plotly_all_s_db_sensors_plot <- ggplotly(all_s_db_sensors_plot)
```

```{r}
#exporting to html
htmlwidgets::saveWidget(plotly_all_s_db_sensors_plot, "all_s_db_sensors_plot.html")
```

```{r}
#exporting to powerpoint - Decided not to use!
all_s_db_sensors_plot_dml <- rvg::dml(ggobj = all_s_db_sensors_plot)

#initializing powerpoint slide
officer::read_pptx() %>%
  # add slide ----
  officer::add_slide() %>%
  # specify object and location of object ----
  officer::ph_with(all_s_db_sensors_plot_dml, ph_location()) %>%
  # export slide -----
  base::print(target = "/Users/erikalee/Documents/CSU_Classes/R_work/nsf_project_code/nsf_project/graphics/all_s_db_sensors_plot.pptx")
```

```{r}
#combinging DB plots into one image and then save it in plots window! - decided not to use!
library(ggplot2)
library(cowplot)

combined_db_plots <- plot_grid(all_n_db_sensors_plot, all_s_db_sensors_plot, nrow = 2) 

print(combined_db_plots)
```

```{r}
##Creating combined N/S DB Sensor plots

plotly_all_s_db <- ggplotly(all_s_db_sensors_plot)
plotly_all_n_db <- ggplotly(all_n_db_sensors_plot)

# Combine the two plots vertically
combined_plot <- subplot(plotly_all_n_db, plotly_all_s_db, nrows = 2, shareX = TRUE)

# Set layout for the combined plot
combined_ns_db_sensors <- layout(combined_plot, title = "Transitional & Persistent North and South DB Sensors",
                        xaxis = list(title = "Datetime"),
                        yaxis = list(title = "Temp (C)"))

# Display the combined plot
combined_ns_db_sensors
```

```{r}
##exporting to html... have not done this yet! Fix colors first?? 
```

```{r}
##creating dataframes for pers_n_gb and trans_n_gb with two trees per dataframe, then combining into one dataframe 
pers_n_gb_sensors <- pers_n_gb_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "persistent") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "gb_s_tree",
    tree_name == "gb_e" ~ "gb_e_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  filter(!(burn_status == "gb_w"))

trans_n_gb_sensors <- trans_n_gb_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "transitional") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "gb_s_tree",
    tree_name == "gb_n" ~ "gb_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))

```

```{r}
##creating dataframes for pers_s_gb and trans_s_gb with two trees per dataframe, then combining into one dataframe 
pers_s_gb_sensors <- pers_s_gb_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "persistent") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "gb_s_tree",
    tree_name == "gb_e" ~ "gb_e_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  #removing gb_w sensor from this dataframe
  filter(!(burn_status == "gb_w"))

trans_s_gb_sensors <- trans_s_gb_temp %>%
  filter(datetime >= "2024-01-31 12:00:00") %>%
  select(-"sensor_id") %>%
  mutate(zone = "transitional") %>%
  mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "gb_s_tree",
    tree_name == "gb_n" ~ "gb_n_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#plotting all_s_gb_sensors_plot 

all_s_gb_sensors_plot <- ggplot() +
  geom_line(data = trans_s_gb_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Transitional"), alpha = 0.5) +
  geom_line(data = pers_s_gb_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Persistent"), alpha = 0.3) +
  scale_color_manual(values = c("blue", "blue", "red", "red"), name = "burnstatus_treename,") +  
  scale_linetype_manual(values = c("solid", "dashed"), name = "Zone") +  
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent Green Burn Tree South Sensors")

ggplotly(all_s_gb_sensors_plot)

plotly_all_s_gb_sensors_plot <- ggplotly(all_s_gb_sensors_plot)
```

```{r}
#exporting to html
htmlwidgets::saveWidget(plotly_all_s_gb_sensors_plot, "all_s_gb_sensors_plot.html")
```

```{r}
all_n_gb_sensors_plot <- ggplot() +
  geom_line(data = trans_n_gb_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Transitional"), alpha = 0.5) +
  geom_line(data = pers_n_gb_sensors, aes(x = datetime, y = temp, color = burn_status, linetype = "Persistent"), alpha = 0.3) +
  scale_color_manual(values = c("blue", "blue", "red", "red"), name = "burnstatus_treename") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "Zone") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent North Aspect Green Burn Tree Sensors")

ggplotly(all_n_gb_sensors_plot)

plotly_all_n_gb_sensors_plot <- ggplotly(all_n_gb_sensors_plot)
```

```{r}
plotly_all_n_gb_sensors_plot <- ggplotly(all_n_gb_sensors_plot)
```

```{r}
#exporting to html
htmlwidgets::saveWidget(plotly_all_n_gb_sensors_plot, "all_n_gb_sensors_plot.html")
```

```{r}
#combining plots to make one page html for GB N/S and DB N/S - did not work very well as the legends combine and the titles disappear
library(patchwork)

combined_GB_plots <- subplot(
  plotly_all_n_gb_sensors_plot, 
  plotly_all_s_gb_sensors_plot, 
  nrows = 2
)

#exporting as html
htmlwidgets::saveWidget(combined_GB_plots, "combined_GB_plots.html")
```

\

\
