---
title: "tree_temp_wx_combined_plots"
author: "Erika Lee"
date: "2024-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set up
library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)
library(htmlwidgets)
library(patchwork)
library(here)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

### Persistent Zone

```{r}
#creating a combined N/S sensors dataframe for persistent trees

pers_b_ns_sensors <- pers_b_aspects %>%
  filter(datetime>= ymd_hms("2023-12-19 07:00:00", tz = 'MST') & datetime <= ymd_hms("2024-01-10 00:00:00", tz = 'MST')) %>%
  filter(aspect %in% c("north", "south")) %>%
  select(-sensor_id) %>%
  mutate(burn_status = case_when(
    tree_name == "gb_w" ~ "GB",
    tree_name == "gb_s" ~ "GB",
    tree_name == "gb_e" ~ "GB",
    tree_name == "db_n" ~ "DB",
    tree_name == "db_s" ~ "DB",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(full_name = case_when(
    tree_name == "gb_w" & aspect == "north" ~ "n_gb_w_tree",
    tree_name == "gb_s" & aspect == "north" ~ "n_gb_s_tree",
    tree_name == "gb_e" & aspect == "north" ~ "n_gb_e_tree",
    tree_name == "gb_w" & aspect == "south" ~ "s_gb_w_tree",
    tree_name == "gb_s" & aspect == "south" ~ "s_gb_s_tree",
    tree_name == "gb_e" & aspect == "south" ~ "s_gb_e_tree",
    tree_name == "db_n" & aspect == "north" ~ "n_db_n_tree",
    tree_name == "db_s" & aspect == "north" ~ "n_db_s_tree",
    tree_name == "db_n" & aspect == "south" ~ "s_db_n_tree",
    tree_name == "db_s" & aspect == "south" ~ "s_db_s_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))

#creating individual tree sensors for south db/gb sensors
pers_s_gb_e <- pers_b_ns_sensors %>%
  filter(full_name == "s_gb_e_tree")

pers_s_db_s <- pers_b_ns_sensors %>%
  filter(full_name == "s_db_s_tree")

#creating individual tree dataframe for north gb/db sensors

pers_n_gb_e <- pers_b_ns_sensors %>%
  filter(full_name == "n_gb_e_tree")

pers_n_db_e <- pers_b_ns_sensors %>%
  filter(full_name == "n_db_s_tree")

#creating a pers_unburned dataframe of south sensors only to use in combined plot - south unburned tree, south sensor

pers_s_ub_s <- pers_ub_s_tree %>%
  filter(aspect == "south") %>%
  mutate(full_name = "s_ub_s_tree")
```

```{r}
#creating one dataframe with tree temp, radiation and air temp for one tree
selected_pers_b_tree_rad_airT <- pers_b_ns_sensors %>%
  filter(aspect == "south" & tree_name %in% c("gb_e", "db_s")) %>%
  mutate(full_name = case_when(
    tree_name == "gb_e" & aspect == "south" ~ "s_gb_e_tree",
    tree_name == "db_s" & aspect == "south" ~ "s_db_s_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  full_join(pers_burned_rad_air, by = 'datetime') %>%
  filter(datetime>= ymd_hms("2023-12-19 07:00:00") & datetime <= ymd_hms("2024-01-10 00:00:00"))
```

```{r}
#plotting tree temp and air temp together
combined_pers_b_treeairT_plot <- ggplot() +
  geom_line(data = pers_s_gb_e, aes(x = datetime, y = temp, group = "s_gb_e_tree", color = "s_gb_e_tree", ), linetype = "solid", alpha = 0.5) + 
  geom_line (data = pers_s_db_s, aes(x = datetime, y = temp, group = "s_db_s_tree", color = "s_db_s_tree"), linetype = "dashed", alpha = 0.5) +
    #removed unburned version because we don't have datetime stamps that match yet...
  #geom_line (data = pers_s_ub_s, aes(x = datetime, y = temp, group = "s_ub_s_tree", color = "s_ub_s_tree"), linetype = "solid", alpha = 0.5) +
  geom_line(data = selected_pers_b_tree_rad_airT, aes(x = datetime, y = AirTC_Avg, color = "AirT (C)"), linetype = "solid", alpha = 0.5) +
  labs(x = "Datetime", y = "Temp (C)", title = "Persistent South Aspect Sensors Tree Temps and Weather") +
  
  theme_minimal() +
 scale_color_manual(values = c("s_gb_e_tree" = "red", "s_db_s_tree" = "blue", "AirT (C)" = "green")) +
  guides(linetype = guide_legend(title = "Line Type"), color = guide_legend(title = "Color"))

ggplotly(combined_pers_b_treeairT_plot)
```

```{r}
#creating seperate radiation plot
radiation_plot <- ggplot() +
  geom_line(data = selected_pers_b_tree_rad_airT, aes(x = datetime, y = SWin_Avg, color = "SWin_Avg")) +
  labs(x = "Datetime", y = "SWin (w/m2)", title = "Incoming SW Radiation") +
  scale_color_manual(values = c("SWin_Avg" = "orange")) +
  guides(linetype = guide_legend(title = "Line Type"), color = guide_legend(title = "Color"))

ggplotly(radiation_plot)
```

```{r}
## creating a combined plot of both plots on one page!
# Convert ggplot objects to plotly objects
plotly_pers_b_treeairT <- ggplotly(combined_pers_b_treeairT_plot)
plotly_pers_b_rad <- ggplotly(radiation_plot)

# Combine the two plots vertically
combined_plot <- subplot(plotly_pers_b_treeairT, plotly_pers_b_rad, nrows = 2, shareX = TRUE)

# Set layout for the combined plot
combined_plot <- layout(combined_plot, title = "Persistent South Aspect Sensors Tree Temps, Air Temp and Incoming SW radiation",
                        xaxis = list(title = "Datetime"),
                        yaxis = list(title = "Temp (C)"), 
                        yaxis2 = list(title = "SWin (W/m2)"))

# Display the combined plot
combined_plot
```

```{r}
#exporting as a html page
htmlwidgets::saveWidget(combined_plot, "combined_pers_b_south_senors_weather_data.html")
```

### Transitional Zone

Transitional Tree temps, air temp and SWin comparison

```{r}
#creating individual tree sensors for south db/gb sensors
trans_s_gb_s <- trans_b_ns_sensors %>%
  filter(full_name == "s_gb_s_tree")

trans_s_db_s <- trans_b_ns_sensors %>%
  filter(full_name == "s_db_s_tree")

#creating individual tree dataframe for north gb/db sensors on south tree

trans_n_gb_s <- trans_b_ns_sensors %>%
  filter(full_name == "n_gb_s_tree")

trans_n_db_s <- trans_b_ns_sensors %>%
  filter(full_name == "n_db_s_tree")

#creating a pers_unburned dataframe of south sensors only to use in combined plot - south unburned tree, south sensor

trans_s_ub_e <- trans_ub_e_tree %>%
  filter(aspect == "south") %>%
  mutate(full_name = "s_ub_e_tree") %>%
  filter(datetime >= ymd_hms("2024-02-01 00:00:00", tz = 'MST') & datetime <= ymd_hms("2024-02-19 00:00:00", tz = 'MST'))
```

```{r}
#plotting tree temp and air temp together
combined_trans_b_treeairT_plot <- ggplot() +
  geom_line(data = trans_s_gb_s, aes(x = datetime, y = temp, group = "s_gb_s_tree", color = "s_gb_s_tree", ), linetype = "solid", alpha = 0.5) + 
  geom_line (data = trans_s_db_s, aes(x = datetime, y = temp, group = "s_db_s_tree", color = "s_db_s_tree"), linetype = "dashed", alpha = 0.5) +
    #removed unburned version because we don't have datetime stamps that match yet...
  geom_line (data = trans_s_ub_e, aes(x = datetime, y = temp, group = "s_ub_s_tree", color = "s_ub_e_tree"), linetype = "solid", alpha = 0.5) +
  geom_line(data = trans_burned_rad_air, aes(x = datetime, y = AirT_C, color = "AirT (C)"), linetype = "solid", alpha = 0.5) +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional South Aspect Sensors Tree Temps and Weather",  color = "sensoraspect_burnstatus_treename") +
  
  theme_minimal() +
 scale_color_manual(values = c("s_gb_s_tree" = "red", "s_db_s_tree" = "blue", "s_ub_e_tree" = "black", "AirT (C)" = "green")) + guides(linetype = guide_legend(title = "Line Type"))  # Removed the color legend title since we manually specified it in labs()

ggplotly(combined_trans_b_treeairT_plot)
```

```{r}
trans_radiation_plot <- ggplot(data = trans_burned_rad_air) +
  geom_line(aes(x = datetime, y = SWin_Avg, color = "SWin_Avg")) +
  labs(x = "Datetime", y = "SWin (w/m2)", title = "Incoming SW Radiation") +
  scale_color_manual(values = c("SWin_Avg" = "orange")) +
  guides(linetype = guide_legend(title = "Line Type"))

ggplotly(trans_radiation_plot)
```

```{r}
## transitional - creating a combined plot of both plots on one page!
# Convert ggplot objects to plotly objects
plotly_trans_b_treeairT <- ggplotly(combined_trans_b_treeairT_plot)
plotly_trans_b_rad <- ggplotly(trans_radiation_plot)

# Combine the two plots vertically
trans_combined_plot <- subplot(plotly_trans_b_treeairT, plotly_trans_b_rad, nrows = 2, shareX = TRUE)

# Set layout for the combined plot
trans_combined_plot <- layout(combined_plot, title = "Transitional South Aspect Sensors Tree Temps, Air Temp and Incoming SW radiation",
                        xaxis = list(title = "Datetime"),
                        yaxis = list(title = "Temp (C)"), 
                        yaxis2 = list(title = "SWin (W/m2)"),
                       showlegend = TRUE,  # Ensure legend is shown
         legend = list(title = list(text = "sensoraspect_burnstatus_treename")))  # Assigning the legend title

# Display the combined plot
trans_combined_plot
```

```{r}
#exporting as a html page
htmlwidgets::saveWidget(combined_plot, "combined_trans_b_south_senors_weather_data.html")
```

```{r}
#creating new dataframe for persistent site comparison with the correct timeframe 

pers_b_ns_sensors_V2 <- pers_b_aspects %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  select(-sensor_id) %>%
  mutate(burn_status = case_when(
    tree_name == "gb_w" ~ "GB",
    tree_name == "gb_s" ~ "GB",
    tree_name == "gb_e" ~ "GB",
    tree_name == "db_n" ~ "DB",
    tree_name == "db_s" ~ "DB",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(full_name = case_when(
    tree_name == "gb_w" & aspect == "north" ~ "n_gb",
    tree_name == "gb_s" & aspect == "north" ~ "n_gb",
    tree_name == "gb_e" & aspect == "north" ~ "n_gb",
    tree_name == "gb_w" & aspect == "south" ~ "s_gb",
    tree_name == "gb_s" & aspect == "south" ~ "s_gb",
    tree_name == "gb_e" & aspect == "south" ~ "s_gb",
    tree_name == "db_n" & aspect == "north" ~ "n_db",
    tree_name == "db_s" & aspect == "north" ~ "n_db",
    tree_name == "db_n" & aspect == "south" ~ "s_db",
    tree_name == "db_s" & aspect == "south" ~ "s_db",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#creating a ns combined dataframe
trans_b_ns_sensors <- trans_b_aspects %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  select(-sensor_id) %>%
  mutate(burn_status = case_when(
    tree_name == "gb_n" ~ "GB",
    tree_name == "gb_s" ~ "GB",
    tree_name == "db_n" ~ "DB",
    tree_name == "db_s" ~ "DB",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(full_name = case_when(
    tree_name == "gb_n" & aspect == "north" ~ "n_gb_n_tree",
    tree_name == "gb_s" & aspect == "north" ~ "n_gb_s_tree",
    tree_name == "gb_n" & aspect == "south" ~ "s_gb_n_tree",
    tree_name == "gb_s" & aspect == "south" ~ "s_gb_s_tree",
    tree_name == "db_n" & aspect == "north" ~ "n_db_n_tree",
    tree_name == "db_s" & aspect == "north" ~ "n_db_s_tree",
    tree_name == "db_n" & aspect == "south" ~ "s_db_n_tree",
    tree_name == "db_s" & aspect == "south" ~ "s_db_s_tree",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#comparison individual trees with ns sensors for pers and transitonal zones
trans_b_ns_gb_sensors <- trans_b_ns_sensors %>%
  filter(tree_name %in% c("gb_s")) %>%
  mutate(zone = "transitional")
  
pers_b_ns_gb_sensors <- pers_b_ns_sensors_V2 %>%
  filter(tree_name %in% c("gb_s")) %>%
  mutate(zone = "persistent")

trans_b_ns_db_sensors <- trans_b_ns_sensors %>%
  filter(tree_name %in% c("db_s")) %>%
  mutate(zone = "transitional")

pers_b_ns_db_sensors <- pers_b_ns_sensors_V2 %>%
  filter(tree_name %in% c("db_s")) %>%
   mutate(zone = "persistent")
```

```{r}
#plotting individual tree comparisons between zones

## pers vs trans gb sensors
pers_trans_ns_gb_plot <- ggplot() + 
geom_line(data = trans_b_ns_gb_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "transitional"), alpha = 0.5) +
  geom_line(data = pers_b_ns_gb_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "persistent"), alpha = 0.5) +
scale_color_manual(values = c("cyan2", "red", "cyan2", "red"), name = "sensoraspect_burnstatus,") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "zone") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent Green Burn Sensors by Aspect")

ggplotly(pers_trans_ns_gb_plot)

## pers vs trans db sensors
pers_trans_ns_db_plot <- ggplot() + 
geom_line(data = trans_b_ns_db_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "transitional"), alpha = 0.5) +
  geom_line(data = pers_b_ns_db_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "persistent"), alpha = 0.5) +
scale_color_manual(values = c("blue", "brown3", "blue", "brown3"), name = "sensoraspect_burnstatus,") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "zone") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional and Persistent Dead Burn Sensors by Aspect")

ggplotly(pers_trans_ns_db_plot)
```

```{r}
#creating plotly objects and combining plots
# Convert ggplot objects to plotly objects
plotly_pers_trans_ns_db <- ggplotly(pers_trans_ns_db_plot)
plotly_pers_trans_ns_gb <- ggplotly(pers_trans_ns_gb_plot)

# Combine the two plots vertically
combined_ns_gbdb_plot <- subplot(plotly_pers_trans_ns_db, plotly_pers_trans_ns_gb, nrows = 2, shareX = TRUE)

# Set layout for the combined plot
combined_ns_gbdb_plot <- layout(
  combined_ns_gbdn_plot,
  title = list(text = "Transitional and Persistent Sensor Comparison, Dead Burned (top) & Green Burned (bottom)"),
  xaxis = list(title = "Datetime"),
  yaxis = list(title = "Temp (C)"),
  yaxis2 = list(title = "Temp (C)")
)
```

```{r}
#exporting as a html page
htmlwidgets::saveWidget(combined_ns_gbdb_plot, "combined_ns_gbdb_plot.html")
```

### GB vs DB Comparison

```{r}
#transitional gb and db combined dataframe
trans_b_gbdb <- trans_b_aspects %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  filter(tree_name %in% c("gb_s", "db_s")) %>%
  select(-sensor_id) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(full_name = case_when(
    tree_name == "gb_s" & aspect == "north" ~ "n_gb",
    tree_name == "gb_s" & aspect == "south" ~ "s_gb",
    tree_name == "db_s" & aspect == "north" ~ "n_db",
    tree_name == "db_s" & aspect == "south" ~ "s_db",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
    mutate(burn_status = case_when(
    tree_name == "gb_s" ~ "trans_GB",
    tree_name == "db_s" ~ "trans_DB", TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  mutate(zone = "transitional")
```

```{r}
#persistent gb and db combined dataframe
pers_b_gbdb <- pers_b_aspects %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  filter(tree_name %in% c("gb_e", "db_s")) %>%
  select(-sensor_id) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(full_name = case_when(
    tree_name == "gb_e" & aspect == "north" ~ "n_gb",
    tree_name == "gb_e" & aspect == "south" ~ "s_gb",
    tree_name == "db_s" & aspect == "north" ~ "n_db",
    tree_name == "db_s" & aspect == "south" ~ "s_db",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
      mutate(burn_status = case_when(
    tree_name == "gb_e" ~ "pers_GB",
    tree_name == "db_s" ~ "pers_DB", TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  )) %>%
  mutate(zone = "persistent")
```

```{r}
#plotting gb vs db by zone
##transitional
trans_ns_gbdb_plot <- ggplot() + 
geom_line(data = trans_b_gbdb, aes(x = datetime, y = temp, color = aspect, linetype = burn_status), alpha = 0.5) +
  #geom_line(data = pers_b_ns_db_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "persistent"), alpha = 0.5) +
scale_color_manual(values = c("blue", "red", "blue", "red"), name = "sensoraspect,") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "zone_burnstatus") +
  labs(x = "Datetime", y = "Temp (C)", title = "Transitional GB vs DB north and south aspect sensors")

ggplotly(trans_ns_gbdb_plot)

##persistent
pers_ns_gbdb_plot <- ggplot() + 
geom_line(data = pers_b_gbdb, aes(x = datetime, y = temp, color = aspect, linetype = burn_status), alpha = 0.5) +
  #geom_line(data = pers_b_ns_db_sensors, aes(x = datetime, y = temp, color = full_name, linetype = "persistent"), alpha = 0.5) +
scale_color_manual(values = c("deepskyblue", "deeppink4", "deepskyblue", "deeppink4"), name = "sensoraspect,") +
  scale_linetype_manual(values = c("solid", "dashed"), name = "zone_burnstatus") +
  labs(x = "Datetime", y = "Temp (C)", title = "Persistent GB vs DB north and south aspect sensors")

ggplotly(pers_ns_gbdb_plot)
```

```{r}
#creating plotly objects and combining plots
# Convert ggplot objects to plotly objects
plotly_trans_ns_gbdb_2 <- ggplotly(trans_ns_gbdb_plot)
plotly_pers_ns_gbdb_2 <- ggplotly(pers_ns_gbdb_plot)

#fixing legends to individual plots in combined plot
#plotly_trans_ns_gbdb_2 <- plotly_trans_ns_gbdb_2 %>% layout(showlegend = TRUE)
#plotly_pers_ns_gbdb_2 <- plotly_pers_ns_gbdb_2 %>% layout(showlegend = TRUE)

# Combine the two plots vertically
combined_trans_pers_gbdb <- subplot(plotly_trans_ns_gbdb_2, plotly_pers_ns_gbdb_2, nrows = 2, shareX = TRUE)

combined_trans_pers_gbdb <- layout(
  combined_trans_pers_gbdb,
  title = list(text = "Transitional(top) and Persistent(bottom) Green Burn vs Dead Burn Aspect Comparison"),
  xaxis = list(title = "Datetime"),
  yaxis = list(title = "Temp (C)"),
  yaxis2 = list(title = "Temp (C)")
)

combined_trans_pers_gbdb
```

```{r}
#exporting as a html page
htmlwidgets::saveWidget(combined_trans_pers_gbdb, "combined_trans_pers_gbdb.html")
```

### Burned vs Unburned - Persistent

```{r}
#comparing south tree, n and s sensors of burned vs unburned
#datatable for pers_e_tree
pers_gbdb_tree <- pers_b_aspects %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  filter(tree_name %in% c("gb_e", "db_s")) %>%
  select(-sensor_id) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(aspect_bs = case_when(
    tree_name == "gb_e" & aspect == "north" ~ "n_gb",
    tree_name == "gb_e" & aspect == "south" ~ "s_gb",
    tree_name == "db_s" & aspect == "north" ~ "n_db",
    tree_name == "db_s" & aspect == "south" ~ "s_db",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
      #mutate(burn_status = case_when(
    #tree_name == "gb_e" ~ "pers_GB",
    #tree_name == "db_s" ~ "pers_DB", TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  #)) 

pers_ub_s_tree_2 <- pers_ub_s_tree %>%
  filter(datetime>= ymd_hms("2024-02-01 00:00:00") & datetime <= ymd_hms("2024-02-19 00:00:00")) %>%
  filter(aspect %in% c("north", "south")) %>%
  filter(tree_name == "ub_s") %>%
  select(-sensor_id) %>%
  #creating a new column with aspect_burnstatus_treename
  mutate(aspect_bs = case_when(
    tree_name == "ub_s" & aspect == "north" ~ "n_ub",
    tree_name == "ub_s" & aspect == "south" ~ "s_ub",
    TRUE ~ tree_name  # Keep the original value if it doesn't match the conditions
  ))
```

```{r}
#plotting burned vs ub trees
install.packages('RColorBrewer')

library(RColorBrewer)

# Define color-blind friendly color palette from ColorBrewer
color_palette <- brewer.pal(3, "Dark2")  # 3 colors for three distinct values of tree_name

# Create the plot with color-blind friendly colors
pers_b_ub_plot <- ggplotly(
  ggplot() +
    geom_line(data = pers_ub_s_tree_2, aes(x = datetime, y = temp, color = tree_name, linetype = aspect), alpha = 0.8) + 
    geom_line(data = pers_gbdb_tree, aes(x = datetime, y = temp, color = tree_name, linetype = aspect), alpha = 0.6) +
    scale_color_manual(values = color_palette, name = "burnstatus_treename,") +
    labs(x = "Datetime", y = "Temp (C)", title = "Persistent green burned, dead burned and unburned tree sensor comparison, including N and S sensors") +
    scale_linetype_manual(values = c("solid", "dashed"), name = "Aspect") +  # Flipped the order of linetypes
    labs(linetype = "aspect")  # Manually setting the legend title
)

ggplotly(pers_b_ub_plot)
```

```{r}
#converting to a plotly
plotly_pers_b_ub <- ggplotly(pers_b_ub_plot)

#exporting as a html page - currently saving in N-drive field data folder, then I am moving it to my personal project folder on computer
htmlwidgets::saveWidget(plotly_pers_b_ub, "persistent_burned_unburned_comparison.html")
```
