---
title: "wx_data_processing_code"
author: "Erika Lee"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#packages <- c('tidyverse',
             # 'lterdatasampler', 'dplyr', 'ggplot2', 'readr', #'readxl', 'lubridate', 'plotly', 'openxlsx', 'plotly')

#install.packages(packages)

library(tidyverse)
library(lterdatasampler)
library(dplyr)
library(ggplot2)
library(readr)
library(readxl)
library(lubridate)
library(plotly)
library(openxlsx)
library(plotly)
library(rstatix)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

## Weather Station Data

### Trans Burned Met (Forested)

```{r}
#trans_burned_met weather station data
trans_burned_met=read_excel('nsf/trans_burned_met/trans_burned_met_composite.xlsx')

trans_burned_met$Date = as_date(trans_burned_met$datetime, tz="MST", format="%m/%d/%Y %H:%M")
```

### Trans Burned (Clearing) - Hourly

```{r}
#read in trans_burned weather station data - 30 minute data
trans_burned_wx_composite = read_excel('nsf/trans_burned/trans_burned_wx_composite.xlsx')

#convert datetime column to date/time
trans_burned_wx_composite$datetime <- as.POSIXct(trans_burned_wx_composite$datetime, tz = "MST", format = "%m/%d/%Y %H:%M")
```

### Trans Burned (Clearing) - 15 min

```{r}
#read in 15 minute trans_burned weather station data, minus the geonor data

trans_burned_wx_15min_r = read_excel('nsf/trans_burned/trans_burned_wx_15min.xlsx')

#convert datetime column to date/time
trans_burned_wx_15min_r$datetime <- as.POSIXct(trans_burned_wx_15min_r$datetime, tz = "MST", format = "%m/%d/%Y %H:%M")

write.xlsx(trans_burned_wx_15min_r, "nsf/trans_burned/trans_burned_wx_15min_r.xlsx")
```

### Trans Burned Geonor

```{r}
#read in geonor data
trans_burned_geonor_composite = read_excel('nsf/trans_burned/trans_burned_geonor_composite.xlsx')

#convert datetime column to date/time
trans_burned_geonor_composite$datetime <- as.POSIXct(trans_burned_geonor_composite$datetime, tz = "MST", format = "%m/%d/%Y %H:%M")

#remove NAN data
trans_burned_geonor_composite <- trans_burned_geonor_composite %>%
  filter(datetime >= "2023-11-03 05:40:00") %>%
  slice(-(1:11))
```

### Pers Burned - Hourly

```{r}
#pers_burned weather station data - set up
pers_burned_wx_fulldata=read_excel('nsf/pers_burned/pers_burned_wx_composite.xlsx')

pers_burned_wx <- pers_burned_wx_fulldata %>%
  mutate(datetime = if_else(grepl("^\\d{4}-\\d{2}-\\d{2}$", TIMESTAMP), ymd(TIMESTAMP), ymd_hms(TIMESTAMP))) %>%
  #above line parses out 0:00:00 timestamps (12 am)
  select(datetime, everything()) %>%
  select(-c(TIMESTAMP, RECORD))
```

### Pers Burned - 15 min

```{r}
pers_burned_wx_15min_fulldata=read_excel('nsf/pers_burned/pers_burned_wx_15min_composite.xlsx')

#changing datetime to mountain from UTC for weather data
corrected_pers_burned_wx_15min <- pers_burned_wx_15min %>%
  mutate(datetime_mountain = with_tz(datetime, "America/Denver")) %>%
filter(datetime_mountain >= ymd_hms("2023-12-07 00:00:00", tz = 'MST') & datetime_mountain <= ymd_hms("2024-01-10 00:00:00", tz='MST')) %>%
  select(datetime_mountain, everything())

#changing the datetime manually to MST for pers_b_15min_wx
pers_burned_wx_15min_r <- pers_burned_wx_15min_fulldata %>%
  mutate(datetime = ymd_hms(TIMESTAMP) - hours(7)) %>%
  filter(datetime >= ymd_hms("2023-12-07 00:00:00", tz = 'MST')) %>% #datetime <= ymd_hms("2024-01-21 00:00:00", tz = 'MST')) %>%
  select(datetime, everything())

#send to n-drive as excel
write.xlsx(pers_burned_wx_15min_r, "nsf/pers_burned/pers_burned_wx_15min_r.xlsx")
```

### Pers Unburned - Hourly

```{r}
#pers_burned weather station data
pers_unburned_fulldata=read_excel('nsf/pers_unburned/pers_unburned_wx_composite.xlsx')

pers_unburned <- pers_unburned_fulldata %>%
  mutate(datetime = if_else(grepl("^\\d{4}-\\d{2}-\\d{2}$", TIMESTAMP), ymd(TIMESTAMP), ymd_hms(TIMESTAMP))) %>%
  #above line parses out 0:00:00 timestamps (12 am)
  select(datetime, everything()) %>%
  select(-c(TIMESTAMP, RECORD))
```

### Pers Burned Rad/Air T dataframe

```{r}
#creating new dataframe for specific dates, radiation and air temp
pers_burned_rad_air<- pers_burned_wx_15min_r %>%
  select("datetime", "TIMESTAMP", "SWin_Avg", "SWout_Avg", "AirTC_Avg")
#datetime column is in MST, TIMESTAMP column is in UTC for this dataframe

write.xlsx(pers_burned_rad_air, "nsf/pers_burned/pers_burned_rad_air.xlsx")
```

### Trans Burned Rad/Air T dataframe

```{r}
#creating new dataframe for specific dates, radiation and air temp
trans_burned_rad_air<- trans_burned_wx_15min_r %>%
  filter(!is.na(SWin_Avg)) %>%
  select("datetime", "SWin_Avg", "SWout_Avg", "AirT_C") %>%
  #rounding SWin and SWout numbers to two decimals
  mutate(
    SWin_Avg = round(as.numeric(SWin_Avg), digits = 2),
    SWout_Avg = round(as.numeric(SWout_Avg), digits = 2)
  ) %>%
  filter(datetime >= ymd_hms("2024-02-01 00:00:00", tz = 'MST'))
  #& datetime <= ymd_hms("2024-02-19 00:00:00", tz = 'MST'))

write.xlsx(trans_burned_rad_air, "nsf/trans_burned/trans_burned_rad_air.xlsx")
```
